version: '3'

# Define services
services:
    # App Service
    app:
        # Configuration for building the docker image for the service
        build:
            context: . # Use an image built from the specified dockerfile in the current directory.
            dockerfile: Dockerfile
        ports:
            - '8080:8080'
        restart: always
        environment: # Pass environment variables to the service
            - HOST=${HOST}
            - DBPORT=${DBPORT}
            - DBUSER=${DBUSER}
            - PASSWORD=${PASSWORD}
            - DBNAME=${DBNAME}
            - REDISHOST=${REDISHOST}
            - REDISPASSWORD=${REDISPASSWORD}
            - AWSREGION=${AWSREGION}
            - AWSBUCKET=${AWSBUCKET}
            - ACCESSKEYID=${ACCESSKEYID}
            - SECRETACCESSKEY=${SECRETACCESSKEY}
